# Generated by Django 5.1.6 on 2025-02-18 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_remove_word_word_main_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="file",
            name="file_index_by_name",
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="file_index_by_format_and_name",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="name",
            new_name="file_name",
        ),
        migrations.RenameField(
            model_name="word",
            old_name="name",
            new_name="word_value",
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["file_name"], name="file_index_by_name"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["active", "file_name"], name="active_file_index_by_name"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["format", "file_name"], name="file_index_by_format_and_name"
            ),
        ),
        migrations.AddIndex(
            model_name="word",
            index=models.Index(
                fields=["word_value", "active"], name="active_word_index"
            ),
        ),
    ]
