# Generated by Django 5.1.6 on 2025-02-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0003_remove_file_file_index_by_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="wordsinfiles",
            index=models.Index(
                fields=["file_connection", "word_connection"],
                name="connect_indx_by_word_and_file",
            ),
        ),
    ]
