# Generated by Django 5.1.6 on 2025-02-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0004_wordsinfiles_connect_indx_by_word_and_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsinfiles",
            name="file_connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="words.file"
            ),
        ),
        migrations.AlterField(
            model_name="wordsinfiles",
            name="word_connection",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="words.word"
            ),
            preserve_default=False,
        ),
    ]
