# Generated by Django 5.1.6 on 2025-02-18 10:31

import words.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0005_alter_wordsinfiles_file_connection_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="wordsinfiles",
            name="connect_indx_by_word_and_file",
        ),
        migrations.RenameField(
            model_name="wordsinfiles",
            old_name="file_connection",
            new_name="file",
        ),
        migrations.RenameField(
            model_name="wordsinfiles",
            old_name="word_connection",
            new_name="word",
        ),
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.FileField(
                upload_to="%Y/%m/%d/", validators=[words.models.validate_file_extension]
            ),
        ),
        migrations.AddIndex(
            model_name="wordsinfiles",
            index=models.Index(
                fields=["file", "word"], name="connect_indx_by_word_and_file"
            ),
        ),
    ]
