# Generated by Django 5.1.6 on 2025-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0007_alter_file_user_file_alter_wordsinfiles_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordsinfiles",
            name="tf_idf",
            field=models.FloatField(default=0),
        ),
    ]
