# Generated by Django 5.1.6 on 2025-02-19 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0008_wordsinfiles_tf_idf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wordsinfiles",
            name="tf_idf",
        ),
    ]
